_BASE_: "Base_S4_DLA.yaml"
MODEL:
  CENTERNET:
    NUM_CLASSES: 1
  WEIGHTS: models/CenterNet-S4_DLA_8x.pth
DATASETS:
  TRAIN: ("balloon_train",)
  TEST: ("balloon_val",)
SOLVER:
  MAX_ITER: 600
  BASE_LR: 0.00025
  IMS_PER_BATCH: 2
  RESET_ITER: true
  WARMUP_ITERS: 20
  STEPS: (300,)