_BASE_: "Base_S4_DLA.yaml"
DEBUG: true
MODEL:
  CENTERNET:
    NUM_CLASSES: 1
  WEIGHTS: models/CenterNet-S4_DLA_8x.pth
DATASETS:
  TRAIN: ("balloon_train",)
  TEST: ("balloon_val",)
SOLVER:
  MAX_ITER: 300
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  BASE_LR: 0.3
  IMS_PER_BATCH: 4
  RESET_ITER: true
  WARMUP_ITERS: 20
  STEPS: ()