_BASE_: "Base-CenterNet2.yaml"
MODEL:
  BACKBONE:
    NAME: "build_p35_fcos_dla_bifpn_backbone"
  BIFPN:
    OUT_CHANNELS: 160
    NUM_LEVELS: 3
    NUM_BIFPN: 4
  DLA:
    NUM_LAYERS: 34
    NORM: "BN"
  FPN:
    IN_FEATURES: ["dla3", "dla4", "dla5"]
  ROI_HEADS:
    NUM_CLASSES: 1
    IN_FEATURES: ["p3", "p4", "p5"]
  CENTERNET:
    NUM_CLASSES: 1
    POST_NMS_TOPK_TEST: 128
    FPN_STRIDES: [8, 16, 32]
    IN_FEATURES: ['p3', 'p4', 'p5']
    SOI: [[0, 64], [48, 192], [128, 1000000]]
  WEIGHTS: models/CenterNet2_DLA-BiFPN-P3_24x.pth
DATASETS:
  TRAIN: ("tea_leaves/train",)
  TEST: ("tea_leaves/val",)
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.003
  STEPS: (300, 1000)
  LR_SCHEDULER_NAME: WarmupCosineLR
  MAX_ITER: 1200
  WARMUP_ITERS: 20
  WARMUP_FACTOR: 0.00025
  RESET_ITER: true
INPUT:
  MIN_SIZE_TRAIN: (256, 288, 320, 352, 384, 416, 448, 480, 512, 544, 576, 608)
  MAX_SIZE_TRAIN: 900
  MAX_SIZE_TEST: 736
  MIN_SIZE_TEST: 512